/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mssd;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Random;
import javax.swing.JFileChooser;
import javax.swing.RowSorter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Rei
 */
public class table extends javax.swing.JFrame {

    /**
     * Creates new form table
     */
    
   String matrix[][]= new String[10000][10000];
    int numFilas;
    int numColumnas;
    public table() {
        initComponents();
      
          DefaultTableModel dfm= new DefaultTableModel();
        tabla=this.tabla;
        tabla.setModel(dfm);
        
        
                RowSorter<TableModel> sorter = new TableRowSorter<TableModel>(dfm);
       tabla.setRowSorter(sorter);
        
        dfm.setColumnIdentifiers(new Object[]{"Dias","Entrega del Proveedor","Inventario inicial","Demanda","Ventas","InventarioFinal","Costo a Ordenar","Costo de llevar inventario","Costo de faltante","Costo total","Costo Promedio"});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDias = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btngenerar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtEntrega = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtOrdenar = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtFaltante = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLlevar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Numero de Dias :");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        btngenerar.setText("Generar");
        btngenerar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btngenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenerarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel2.setText("Entrega de Provedor Semanal:");

        txtEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntregaActionPerformed(evt);
            }
        });

        jLabel3.setText("Costo de ordenar:");

        btnGuardar.setText("Guardar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel4.setText("Costo de Faltante:");

        jLabel5.setText("Costo de Llevar el inventario:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFaltante, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLlevar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(btngenerar)
                .addGap(256, 256, 256)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 336, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(165, 165, 165))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtFaltante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtLlevar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btngenerar)
                    .addComponent(btnSalir)
                    .addComponent(btnGuardar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btngenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerarActionPerformed
        // TODO add your handling code here:
        
        String days = this.txtDias.getText().toString();
        String sentrega=this.txtEntrega.getText().toString();
        String sordenar=this.txtOrdenar.getText().toString();
         String sfaltante=this.txtFaltante.getText().toString();
         String sllevar=this.txtLlevar.getText().toString();
        int dias = Integer.parseInt(days);
        int entregass = Integer.parseInt(sentrega);
        double ordenarss= Double.parseDouble(sordenar);
        double faltantess=Double.parseDouble(sfaltante);
        double llevarss=Double.parseDouble(sllevar);
        operaciones nutella= new operaciones();
        double xi=700;
        double yi=1000;
        
           double [] Dayss = new double [dias];
        double [] entregas = new double [dias];
        double [] inventarioinicial = new double [dias];
       double [] demanda = new double [dias];
        double [] ventas = new double [dias];
        double [] inventariofinal = new double [dias];
        double [] costoaordenar = new double [dias];
        double [] costoinventario = new double [dias];
        double [] costofaltante = new double [dias];
        double [] costototal = new double [dias];
        double [] costopromedio = new double [dias];
        Random rand = new Random(); 
     
        int contador=0;
        float costotot=0;
        inventariofinal[0]=0;
        int  randonum =0,randonum2=0;
        xi=entregass;
        yi=ordenarss;
        for(int i=0;i<dias;i++)
        {
        
        Dayss[i]=i;
        if(Dayss[i]%7==0)
        {
        entregas[i]=xi-inventariofinal[i];
        }
        if(i==0)
        {
        inventarioinicial[i]=inventariofinal[i]+ entregas[i];
        }
        else
        {
         inventarioinicial[i]= inventariofinal[(i-1)]+entregas[i];  
        }

        randonum=rand.nextInt(9999-1500)+1500;
        randonum2=rand.nextInt(9999-1500)+1500;

        double numero=nutella.productosmedios(4,randonum,randonum2,1);
        
              
        //System.out.println(numero);
       
        demanda[i]=(double) (-100*Math.log(1-numero));
       // System.out.println(demanda[i]);
        if(inventarioinicial[i]>demanda[i])
        {
        ventas[i]=demanda[i];
        
        }
        else if( inventarioinicial[i]<=demanda[i])
        {
        ventas[i]=inventarioinicial[i];
        }
    
        inventariofinal[i]=inventarioinicial[i]-demanda[i];
        if(inventariofinal[i]<0)
        {
        inventariofinal[i]=0;    
        }
        if(Dayss[i]%7==0)
        {
        costoaordenar[i]=yi;
        }
        costoinventario[i]=llevarss*(inventarioinicial[i]+inventariofinal[i])/2;
      if(inventarioinicial[i]<=demanda[i])
      {
         costofaltante[i]= faltantess*(demanda[i]-inventarioinicial[i]);
      }
        
        costototal[i]=costoaordenar[i]+costoinventario[i]+costofaltante[i];
        contador=contador+1;
        double costo=costototal[i];
        costopromedio[i]=costopromedio[i]+costo;
        double promedio= costopromedio[i]/contador;
        
    
        
        }

          
               DefaultTableModel dfm= new DefaultTableModel();
        tabla=this.tabla;
        tabla.setModel(dfm);
        
                RowSorter<TableModel> sorter = new TableRowSorter<TableModel>(dfm);
       tabla.setRowSorter(sorter);
               dfm.setColumnIdentifiers(new Object[]{"Dias","Entrega del Proveedor","Inventario inicial","Demanda","Ventas","InventarioFinal","Costo a Ordenar","Costo de llevar inventario","Costo de faltante","Costo total","Costo Promedio"});

        for(int i=0;i<dias;i++)
        {
             dfm.addRow(new Object[]{ Dayss[i], entregas[i],inventarioinicial[i],demanda[i],ventas[i],inventariofinal[i],costoaordenar[i],costoinventario[i],costofaltante[i],costototal[i],costopromedio[i]});
         /*
                     double [] costoaordenar = new double [1000];
        double [] costoinventario = new double [1000];
        double [] costofaltante = new double [1000];
        double [] costototal = new double [1000];
        double [] costopromedio = new double [1000];
             */
        }
        
               numFilas=dfm.getRowCount();
       numColumnas=dfm.getColumnCount();
       boolean isCapturedTheTitles=false;
        System.out.println ("   FILAS ="+numFilas+" COLUMNAS= "+numColumnas);
      // matrix[][]= new String[numFilas][numColumnas];
        for(int rowIndex=0;rowIndex<numFilas;rowIndex++)
        {
            for(int colIndex=0;colIndex<numColumnas;colIndex++)
            {
                
                if(!isCapturedTheTitles){
                    matrix[0][colIndex]=dfm.getColumnName(colIndex);
                    isCapturedTheTitles=(rowIndex>0)?true:false;
                }
            //matrix[rowIndex][colIndex]=(String) dfm.getValueAt(rowIndex,colIndex);
                matrix[rowIndex+1][colIndex]=String.valueOf( dfm.getValueAt(rowIndex,colIndex));
           // System.out.print("\t"+matrix[rowIndex][colIndex]);
            
            }
        }
        
        
        
        
        
        
            
        
        
        
        
        
        
        
          
    }//GEN-LAST:event_btngenerarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntregaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int resultado= fileChooser.showSaveDialog(this);
        if(resultado== JFileChooser.CANCEL_OPTION){
            return;
        }
        File archivo = fileChooser.getSelectedFile();
        try{
            PrintWriter salida= new PrintWriter(new FileWriter(archivo+".csv"));
           // String data[][]=obtenerInformacion();
            for(int i=0;i<matrix.length;i++)
            {
                salida.print(matrix[i][0]);
                for(int j=1;j<matrix[i].length;j++)
                {
                    String word= matrix[i][j];
                    if(word!=null)
                    {
                        salida.print(","+word);
                    }else
                    {
                        salida.print(",");
                    }
                }
                salida.println();
            }
          salida.close(); 
        }catch (IOException io){
            
        }
    }//GEN-LAST:event_btnGuardarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new table().setVisible(true);
            }
        });
    }
    /*
    
    public String[][] obtenerInformacion(int numFilas,int numColumnas)
    {
       int numFilas=dfm.getRowCount();
        int numColumnas=dfm.getColumnCount();
        String matrix[][]= new String[numFilas][numColumnas];
        for(int rowIndex=0;rowIndex<numFilas;rowIndex++)
        {
            for(int colIndex=0;colIndex<numColumnas;colIndex++)
            {
            matrix[rowIndex][colIndex]=(String)dfm.getValueAt(rowIndex,colIndex);
            }
        }
        return matrix;
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btngenerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtDias;
    private javax.swing.JTextField txtEntrega;
    private javax.swing.JTextField txtFaltante;
    private javax.swing.JTextField txtLlevar;
    private javax.swing.JTextField txtOrdenar;
    // End of variables declaration//GEN-END:variables
}
